name: Run Unit Tests

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t scmsh-test -f Dockerfile-test .

      - name: Run tests in Docker
        run: docker run scmsh-test
